---
name: 🐛 Bug Report  
description: Report unexpected behavior or defects.  
title: "🐛 [Bug]: "  
labels: ["bug"]  
body:  
  - type: markdown  
    attributes:  
      value: "Help us fix this issue! Provide details below."  
  - type: textarea  
    attributes:  
      label: Description  
      description: A clear and concise description of the bug.  
  - type: textarea  
    attributes:  
      label: Steps to Reproduce  
      description: |  
        1. Step 1  
        2. Step 2  
---