---
name: ✔️ Task  
description: Track small, actionable work (e.g., dependency upgrades, config changes).  
title: "✔️ [Task]: "  
labels: ["task"]  
body:  
  - type: markdown  
    attributes:  
      value: "Use this template for well-defined, standalone tasks."  

  - type: textarea  
    attributes:  
      label: Description  
      description: What needs to be done?  
      placeholder: |  
        Example:  
        - Upgrade `lodash` to v4.17.21.  
        - Fix typo in README.  
      validations:  
        required: true  

  - type: textarea  
    attributes:  
      label: Steps to Complete  
      description: List actionable steps (numbered).  
      placeholder: |  
        1. Step 1  
        2. Step 2  

  - type: checkboxes  
    attributes:  
      label: Common Subtasks  
      options:  
        - label: Update documentation.  
        - label: Add unit/integration tests.  
        - label: Bump dependencies.  

  - type: textarea  
    attributes:  
      label: Dependencies  
      description: Linked issues, PRs, or blockers.  
      placeholder: |  
        - Depends on #123  
        - Blocked by !456  

  - type: dropdown  
    attributes:  
      label: Priority  
      options:  
        - "🔵 Low"  
        - "🟢 Medium"  
        - "🟠 High"  
        - "🔴 Critical"  
      validations:  
        required: true  
---
